**Task 1.1: Tạo Tensor**

In [1]:
import torch
import numpy as np

# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")

# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")

# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.7360, 0.9743],
        [0.2534, 0.6993]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


**Task 1.2: Các phép toán trên Tensor**  
Thực hiện các phép toán sau và in kết quả:
1. Cộng x_data với chính nó. 
2. Nhân x_data với 5. 
3. Nhân ma trận x_data với x_data.T (ma trận chuyển vị của nó). Sử dụng toán tử @.

In [2]:
print(f"Cộng x_data với chính nó:\n {x_data + x_data}\n")
print(f"Nhân x_data với 5:\n {x_data * 5}\n")
print(f"Nhân ma trận x_data với x_data.T:\n {x_data @ x_data.T}\n")

Cộng x_data với chính nó:
 tensor([[2, 4],
        [6, 8]])

Nhân x_data với 5:
 tensor([[ 5, 10],
        [15, 20]])

Nhân ma trận x_data với x_data.T:
 tensor([[ 5, 11],
        [11, 25]])



**Task 1.3: Indexing và Slicing**  
Từ tensor x_data, hãy:
1. Lấy ra hàng đầu tiên. 
2. Lấy ra cột thứ hai. 
3. Lấy ra giá trị ở hàng thứ hai, cột thứ hai.

In [3]:
print(f"Hàng đầu tiên:\n {x_data[0]}\n")
print(f"Cột thứ hai:\n {x_data[:, 1]}\n")
print(f"Giá trị ở hàng thứ hai, cột thứ hai:\n {x_data[1, 1]}\n")

Hàng đầu tiên:
 tensor([1, 2])

Cột thứ hai:
 tensor([2, 4])

Giá trị ở hàng thứ hai, cột thứ hai:
 4



**Task 1.4: Thay đổi hình dạng Tensor**  
Sử dụng torch.rand để tạo một tensor có shape (4, 4).  
Sau đó, sử dụng hàm view hoặc reshape để biến nó thành một tensor có shape (16, 1).

In [4]:
y_rand = torch.rand((4, 4), dtype=torch.float)
print(f"Random Tensor:\n {y_rand}\n")

y_reshaped = y_rand.view(16, 1)
print(f"Reshaped Tensor (16, 1):\n {y_reshaped}\n")

Random Tensor:
 tensor([[0.7732, 0.2704, 0.0252, 0.1144],
        [0.1405, 0.0717, 0.2638, 0.7749],
        [0.3200, 0.9253, 0.0763, 0.6870],
        [0.2472, 0.4022, 0.8795, 0.1378]])

Reshaped Tensor (16, 1):
 tensor([[0.7732],
        [0.2704],
        [0.0252],
        [0.1144],
        [0.1405],
        [0.0717],
        [0.2638],
        [0.7749],
        [0.3200],
        [0.9253],
        [0.0763],
        [0.6870],
        [0.2472],
        [0.4022],
        [0.8795],
        [0.1378]])



**Task 2.1: Thực hành với** autograd

In [5]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")

# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")

# Thực hiện thêm các phép toán
z = y * y * 3

# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x00000156E081CD00>
Đạo hàm của z theo x: tensor([18.])


**Câu hỏi: Chuyện gì xảy ra nếu bạn gọi z.backward() một lần nữa? Tại sao?**  

Khi gọi `z.backward()` lần thứ hai sẽ báo lỗi vì sau lần tính đạo hàm đầu tiên, PyTorch sẽ giải phóng đồ thị tính toán để tiết kiệm bộ nhớ tức là toàn bộ thông tin về các phép toán cũng như các biến trung gian được sử dụng sẽ bị xóa. Do đó xảy ra lỗi.

**Task 3.1: Lớp** nn.Linear

In [6]:
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều

# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[-0.3952,  0.3218],
        [-0.7549, -0.2589],
        [-0.9819, -0.9282]], grad_fn=<AddmmBackward0>)


**Task 3.2: Lớp** nn.Embedding

In [7]:
# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 0.5037, -1.2455, -0.1622],
        [ 0.2988,  0.2677,  0.8204],
        [-0.6900,  0.1073, -0.8935],
        [-0.8091, -0.5939,  1.3275]], grad_fn=<EmbeddingBackward0>)


**Task 3.3: Kết hợp thành một** nn.Module

In [8]:
from torch import nn
class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        # Định nghĩa các lớp (layer) bạn sẽ dùng
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU() # Hàm kích hoạt
        self.output_layer = nn.Linear(hidden_dim, output_dim)
    def forward(self, indices):
        # Định nghĩa luồng dữ liệu đi qua các lớp
        # 1. Lấy embedding
        embeds = self.embedding(indices)
        # 2. Truyền qua lớp linear và hàm kích hoạt
        hidden = self.activation(self.linear(embeds))
        # 3. Truyền qua lớp output
        output = self.output_layer(hidden)
        return output
    
# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]]) # một câu gồm 4 từ
output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")

Model output shape: torch.Size([1, 4, 2])
